### ISSUE TITLE
Hi! I would love to contribute.

### ISSUE THREAD

**Issue by RammasEchor** [bancodobrasil/stop-analyzing-api#32]
I'm learning Golang, and I would love to contribute to this project!

**Comment by tiagostutz** [comment]
Hi there @RammasEchor !! 👋🏻
Welcome to Stop Analyzing. It will be nice to have your contributions here. 😄 

Let's definitely get something for you to tackle. First read the README instructions and try to bring the project up and running. If you struggle with that, no problem, ask for help in the issue and we will help you.
Please let me know as soon as you put the project running locally and then let's tackle some issues. Ok?

Cheers!

**Comment by RammasEchor** [comment]
Thank you! I forked the project, and cloned it, but when I try to run the command `docker-compose up -d postgres pgadmin` I get this error:

```bash
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 199, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[66913] Failed to execute script docker-compose
```

I have docker version `Docker version 20.10.5, build 55c4c88`, and postgres version `postgres (PostgreSQL) 13.2`

**Comment by tiagostutz** [comment]
It seems to be a problem with docker-compose executable...
Can you check what happens when you run the command:
```
docker-compose --version
```

And also, which python version are you running?

**Comment by RammasEchor** [comment]
Thanks for the help! I get this version for `docker-compose --version`: `docker-compose version 1.29.0, build 07737305`, and I'm running `Python 2.7.16`

**Comment by tiagostutz** [comment]
Nice.!
Try googling for this part of the error:
```
 File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory
```

Usually, the first line of the stack is the best one to Google for a problem. In this case, this search would lead you to this url https://github.com/docker/compose/issues/7896 that might have some useful help.

Try this approach please and let me know the result. 😃

**Comment by RammasEchor** [comment]
Hi! 
That solution worked for me! I didn't had docker running in the background, so after I started it, everything went smoothly.

Just a heads up, in this instruction `sh generate.sh` I got an error, but googling it I found that it happens when you run the script in the vs code terminal, so switching to a normal terminal solved that.

I completed all the instructions, and for the last command I get this output:
```
Stop Analyzing API Command Line

Usage:
  Stop [command]

Available Commands:
  help        Help about any command
  migrate     Import data from external source
  serve       Starts the HTTP REST APIs server

Flags:
  -h, --help   help for Stop

Use "Stop [command] --help" for more information about a command.
```

Does this mean I successfully mounted the project? Thanks!

**Comment by tiagostutz** [comment]
Awesome!! Just run:
```bash
DATABASE_URL=postgresql://user2020:pass2020@localhost:5432/stop-analyzing-api go run main.go serve
```
Now go to your browser and open: http://localhost:7070/v1/choice and check if it returns a JSON.

Now, you've "unlock" a first good and importante issue: documentation. I've opened the issue #33 for you to contribute. Please, go to the issue and comment there sharing your thoughts about the problem and proposition state and, if you want to tackle that, say that you could take it. Then I'll assign that to you.

C ya there!
